version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: test